version: '3'
services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - 5672:5672
      - 15672:15672